apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: project-apani-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysqlapp
        image: mysql:5.7
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql_database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql_password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql_root_password
        volumeMounts:
        - name: mysql-mounted-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: project-apani-node
spec:
  type: LoadBalancer
  # loadBalancerIP: 103.127.136.94
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
