apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: project-apani-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: hibban/apani_node:v1.4
        resources:
          limits:
            memory: "256Mi" # Batasan maksimum penggunaan memori
            cpu: "256m" # Batasan maksimum penggunaan CPU
          requests:
            memory: "128Mi" # Permintaan minimum memori
            cpu: "128m" # Permintaan minimum CPU
        ports:
        - containerPort: 3000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: db_password
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: db_hostname
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: db_name
        - name: DB_DIALECT
          valueFrom:
            secretKeyRef:
              name: secret
              key: db_dialect
        - name: DB_TIMEZONE
          valueFrom:
            secretKeyRef:
              name: secret
              key: db_timezone
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-url
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: secret
              key: port
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: project-apani-node
spec:
  type: LoadBalancer # LoadBalancer means this service is load-balanced across all nodes in the cluster
  selector:
    app: nodeapp
  ports:
  - name: http
    port: 80 #listening port to external load balancer
    targetPort: 3000 #listening port of nodeapp pod
    protocol: TCP # optional protocol
